linters-settings:
  funlen:
    lines: 100
    statements: 50

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    # - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocyclo
    # - gofmt
    # - goimports
    - revive
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    # - rowserrcheck //rowserrcheck is disabled because of generics
    - prealloc
    - exportloopref
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - nlreturn
    - whitespace
    - gocritic
    - exportloopref
    - gocognit
    - gofumpt
    - godot